/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cis43project.swingUI;

import cis43project.model.Administrator;
import cis43project.model.Student;
import cis43project.model.User;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 * @author msingh9001
 * @author bkanungo
 */
public class LoginScreen extends javax.swing.JFrame {
    private String user = "";
    private String password = "";
    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        try {
            Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("./img/logo.png"));
            this.setIconImage(image);
        }
        catch (Exception ex) {
            ex.printStackTrace(System.out);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 650));

        jLabel1.setBackground(new java.awt.Color(153, 102, 255));
        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PATHFINDER");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cis43project/swingUI/img/login_logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Your Journey Begins Here!");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("User:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Password:");
        jLabel5.setToolTipText("");

        jTextField1.setToolTipText("Enter Username");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserEntered(evt);
            }
        });
        jTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TextPropertyChanged(evt);
            }
        });

        jPasswordField1.setToolTipText("Enter Password");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordEntered(evt);
            }
        });
        jPasswordField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TextPropertyChanged(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText(" >");
        jButton1.setToolTipText("Login");
        jButton1.setActionCommand("LoginHandler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginHandler(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginHandler
        
        user = jTextField1.getText();
        password = jPasswordField1.getText();
        // Find if user password match
        if (!(user.isEmpty() || password.isEmpty())) {
            // Check is user and password is valid
            User.openUserFile();
            User usr = new User();
            // System.out.printf("button event user %s pwd %s%n", user, password);
            if (!(usr.findUser(this.user, this.password))) 
                JOptionPane.showMessageDialog(null, 
                        "Invalid user or password entered.");
            else {
                if (usr.getRole().equalsIgnoreCase("student")) {
                    Student student = new Student();
                    student.setUser(user);
                    student.setLastName(usr.getLastName());
                    student.setFirstName(usr.getFirstName());
                    student.setRole(usr.getRole());
                    StudentScreen studentScreen = new StudentScreen(student);
                    studentScreen.setVisible(true);
                    this.setVisible(false);
                }
                else {
                    // Admin 
                    Administrator admin = new Administrator();
                    admin.setUser(user);
                    admin.setFirstName(usr.getFirstName());
                    admin.setLastName(usr.getLastName());
                    admin.setRole(usr.getRole());
                    AdminScreen adminScreen = new AdminScreen(admin);
                    adminScreen.setVisible(true);
                    this.setVisible(false);
                }
            }
                
        }
    }//GEN-LAST:event_LoginHandler

    private void UserEntered(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserEntered
        // Get user entry
        user = evt.getActionCommand();
    }//GEN-LAST:event_UserEntered

    private void PasswordEntered(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordEntered
        // Password Entered
        password = evt.getActionCommand();
    }//GEN-LAST:event_PasswordEntered

    private void TextPropertyChanged(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TextPropertyChanged
        // get the component
        String text;
        Object source = evt.getSource();
        
        if (source == jTextField1) {
            text = jTextField1.getText();
            if (!(text.isEmpty()))
                user = text;
        }
        else if (source == jPasswordField1) {
            text = jPasswordField1.getText();
            if (!(text.isEmpty()))
                password = text;
        }
    }//GEN-LAST:event_TextPropertyChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
